services:
  - type: web
    name: musicmaster-downloader
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    disk:
      name: downloads
      mountPath: /downloads
      sizeGB: 10
